#!/bin/bash
# Generates Nightcap.xcodeproj with the CloudKit transport enabled, signed by
# YOUR team rather than the upstream author's.
#
# Writes a gitignored overlay spec so nothing personal reaches the repo:
# project.yml stays exactly as upstream ships it.
#
# Env (normally supplied by fastlane/.env):
#   NIGHTCAP_TEAM_ID, NIGHTCAP_BUNDLE_PREFIX, NIGHTCAP_ICLOUD_CONTAINER
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

TEAM_ID="${NIGHTCAP_TEAM_ID:?set NIGHTCAP_TEAM_ID}"
PREFIX="${NIGHTCAP_BUNDLE_PREFIX:-com.ahmedramy.nightcap}"
CONTAINER="${NIGHTCAP_ICLOUD_CONTAINER:-iCloud.$PREFIX}"

cat > project.cloud.local.yml <<EOF
# Generated by scripts/generate-cloud-project.sh — do not edit, do not commit.
include:
  - project.yml

targets:
  Nightcap:
    entitlements:
      path: Nightcap/NightcapCloud.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-only: true
        com.apple.security.network.client: true
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.icloud-container-identifiers:
          - $CONTAINER
    settings:
      base:
        DEVELOPMENT_TEAM: $TEAM_ID
        PRODUCT_BUNDLE_IDENTIFIER: $PREFIX
        # Scoped here rather than passed on the xcodebuild command line, which
        # would apply the profile to every target including the SPM ones that
        # cannot take a profile at all.
        CODE_SIGN_STYLE: ${NIGHTCAP_SIGN_STYLE:-Automatic}
        CODE_SIGN_IDENTITY: ${NIGHTCAP_SIGN_IDENTITY:-Apple Development}
        PROVISIONING_PROFILE_SPECIFIER: ${NIGHTCAP_PROFILE:-}
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: \$(inherited) NIGHTCAP_CLOUDKIT
    # The Mac is the only publisher: if it does not link the transport then
    # nothing ever reaches the container and the companions wait forever. Safe to
    # link — NightcapCloudTransport declares every dependency link: false, so it
    # contributes only its own objects, not a second copy of the domain.
    dependencies:
      - target: NightcapCloudTransport_macOS

  # The companions need the container entitlement too, not just the Mac: without
  # it a device build signs fine and then finds no container at runtime, which
  # looks exactly like "the Mac never published".
  NightcapPhone:
    entitlements:
      path: Nightcap/NightcapPhoneCloud.entitlements
      properties:
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.icloud-container-identifiers:
          - $CONTAINER
    settings:
      base:
        DEVELOPMENT_TEAM: $TEAM_ID
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: $PREFIX.phone
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: \$(inherited) NIGHTCAP_CLOUDKIT
    # Safe to link despite the Mac target's note: NightcapCloudTransport declares
    # every dependency link: false, so this adds only its own objects — the
    # domain and package objects still arrive once, via NightcapCompanionUI.
    dependencies:
      - target: NightcapCloudTransport_iOS

  NightcapWatch:
    entitlements:
      path: Nightcap/NightcapWatchCloud.entitlements
      properties:
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.icloud-container-identifiers:
          - $CONTAINER
    settings:
      base:
        DEVELOPMENT_TEAM: $TEAM_ID
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: $PREFIX.watch
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: \$(inherited) NIGHTCAP_CLOUDKIT
    dependencies:
      - target: NightcapCloudTransport_watchOS
EOF

xcodegen --spec project.cloud.local.yml
echo "Generated with team $TEAM_ID, bundle prefix $PREFIX, container $CONTAINER"
